CREATE OR REPLACE VIEW "public"."v_job_ingestion_hotel" AS  SELECT jih.id,
    jih.job_ingestion_id,
    jih.ingestion_type,
    jih.currency_ingested,
    jih.room_nights_total,
    jih.original_unmatched_count,
    jih.original_unmatched_spend_usd,
    jih.unmatched_count,
    jih.unmatched_spend,
    jih.unmatched_spend_usd,
    jih.matched_count,
    jih.matched_spend,
    jih.matched_spend_usd,
    jih.ingestion_status,
    jih.is_dpm,
    jih.status_dpm,
    jih.date_status_dpm,
    jih.is_sourcing,
    jih.status_sourcing,
    jih.date_status_sourcing,
    jih.ingestion_note,
    jih.created,
    jih.modified,
    ji.client_id,
    ji.client_name,
    ji.job_name,
    ji.count_rows,
    ji.data_start_date,
    ji.data_end_date,
    ji.advito_application_template_id,
    ji.template_name,
    ji.advito_application_template_source_id,
    ji.source_name,
    ji.template_note,
    ji.template_category,
    ji.name_last,
    ji.name_first,
    ji.upload_timestamp
   FROM (job_ingestion_hotel jih
     JOIN v_job_ingestion ji ON ((ji.id = jih.job_ingestion_id)));

ALTER TABLE "public"."v_job_ingestion_hotel" OWNER TO "AdvitoAdmin";