 SELECT ahc.id AS stage_activity_hotel_candidate_id,
    ahc.stage_activity_hotel_id,
    ahc.hotel_property_id,
    ahc.match_score,
    ah.chain_name,
    ah.brand_name,
    ah.hotel_name,
    ah.address_line_1,
    ah.city_name,
    ah.state_code,
    ah.country_code,
    ah.phone_number,
    ah.room_spend,
    ah.number_of_nights,
    ah.lanyon_id,
    ah.sabre_property_id,
    ah.apollo_property_id,
    ah.worldspan_property_id,
    ah.amadeus_property_id,
    hp.property_name,
    hp.address1,
    hp.address2,
    hp.city,
    hp.state,
    hp.country,
    hp.phone_primary,
    hp.id_hmf,
    hp.id_lanyon,
    hp.id_max,
    hp.id_travelclick,
    hp.id_amadeus,
    hp.id_apollo,
    hp.id_sabre,
    hp.id_worldspan,
    hpa.id AS alias_id
   FROM (((blops.stage_activity_hotel_candidate ahc
     JOIN blops.stage_activity_hotel ah ON ((ah.id = ahc.stage_activity_hotel_id)))
     JOIN hotel_property hp ON ((hp.id = ahc.hotel_property_id)))
     JOIN hotel_property_alias hpa ON ((hpa.hotel_property_id = ahc.hotel_property_id)))